ALTER TABLE pacientes ALTER COLUMN estado DROP NOT NULL;
ALTER TABLE pacientes ALTER COLUMN cpf DROP NOT NULL;
ALTER TABLE pacientes ALTER COLUMN rg DROP NOT NULL;
ALTER TABLE pacientes ALTER COLUMN cep DROP NOT NULL;
ALTER TABLE pacientes ALTER COLUMN cpf TYPE VARCHAR(24);
